### ISSUE TITLE
When I run the script I am getting this : error at find_elements method : invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by izzyjere** [shaikhsajid1111/facebook_page_scraper#26]

**Comment by izzyjere** [comment]
it works now

**Comment by LChito** [comment]
Hello @izzyjere how do you resolve the problem. When i run the script im still getting the error. Also @shaikhsajid1111 there some pages im still having "No posts were found!". Please let me now how can I fix these two problems. 

Thx!

**Comment by shaikhsajid1111** [comment]
@LChito do you mind sharing one of those page so I can recreate the issue?

**Comment by LChito** [comment]
@shaikhsajid1111 Hello, sorry for the late. This 2 pages I used that show me that problems:
- https://www.facebook.com/brasil.farmacias ("No posts were found")
- https://www.facebook.com/FarmaciasSanRafaelYLibreriasMarcela ("error at find_elements method : invalid literal for int() with base 10: '')

**Comment by shaikhsajid1111** [comment]
Hey, I've checked the issue.
1. https://www.facebook.com/brasil.farmacias - This Page isn't available. 
![image](https://user-images.githubusercontent.com/44086997/193989356-ee76d801-8960-421f-b4b0-d4926b1c04ed.png)
2. https://www.facebook.com/FarmaciasSanRafaelYLibreriasMarcela - Yeah selector was outdated, I've fixed this as well and will push an update in a couple of hours. 

If you're having an issue with this scraper, consider running that page in headful mode by passing `headless=False` in the constructor of `Facebook_scraper`. Like so, `crawler = Facebook_scraper("FarmaciasSanRafaelYLibreriasMarcela", posts_count=10, browser="firefox",headless=False)`

**Comment by LChito** [comment]
Sorry @shaikhsajid1111 can you show me how I have to put this code on Python. Also, I have to update the version in my repository?

**Comment by shaikhsajid1111** [comment]
Just pass headless=False in the Facebook_scraper like I have mentioned in the code above. While running the code the browser window wil open and you can see what's really happening. 
Example:
```
crawler = Facebook_scraper("FarmaciasSanRafaelYLibreriasMarcela", posts_count=10, browser="firefox",headless=False)
data = crawler.scrap_to_json()
print(data)
```

BTW, are you using different Facebook language?, This crawler shall work with English(UK)

**Comment by LChito** [comment]
@shaikhsajid1111 Maybe it continue happen because I have the facebook in Spanish. How can I change de language?
![Ejemplo](https://user-images.githubusercontent.com/114953887/194087555-486b5687-f259-4791-845d-7ffa11577a03.png)

**Comment by shaikhsajid1111** [comment]
https://www.facebook.com/help/327850733950290/manage-your-facebook-language-settings/?helpref=platform_switcher&cms_platform=www

I think this may help 😅

**Comment by LChito** [comment]
I'm still having the problem 😞 were do you download th firefox driver? Because I'm using Chormedriver

**Comment by shaikhsajid1111** [comment]
Logs are still same like the one you posted screenshot above?, I mean I changed logs format but in your screenshot shows still the old format

**Comment by LChito** [comment]
@shaikhsajid1111 can you show me? Because I really don't undertstand you right now, im sorry 😢

**Comment by shaikhsajid1111** [comment]
When you run the crawler, is it still printing the same thing in same format?, Or the format looks different?

**Comment by LChito** [comment]
It's the same one

**Comment by LChito** [comment]
What's the newest version to install?

**Comment by shaikhsajid1111** [comment]
@LChito are you new to Python?, Are you coming from different programming language?

**Comment by LChito** [comment]
THANK YOU SO MUCH! Finally it works! Only the reactions doesn't works properly.

**Comment by shaikhsajid1111** [comment]
Reactions might not be working because it finds reaction by keywords like "50 Cares", so If it's not in English you will get 0 as the output. That's the very reason I was suggesting to use English

**Comment by LChito** [comment]
@shaikhsajid1111 I already change de language to English UK in my facebook like the personal but in the scrapper I continue looking it in spanish, what changes I have to do?

**Comment by shaikhsajid1111** [comment]
It is happening probably because of the region. I even face the same issue, I fix it by inserting `en-gb` at the prefix of the link so it look something like this https://en-gb.facebook.com/
