### ISSUE TITLE
Scrapping multiple page_name

### ISSUE THREAD

**Issue by kokohandoko00** [shaikhsajid1111/facebook_page_scraper#45]
I want to scrap multiple page names, I define a list of page name on a variable

`page_names = ["pagename1", "pagename2", "pagename3"]`

and then I iterate Facebook_scraper through multiple page_names with this code

`results=[]
posts_count = 2
browser = "firefox"
proxy = "IP:PORT" #if proxy requires authentication then user:password@IP:PORT
timeout = 600 #600 seconds
headless = True

for name in page_names:
    meta_ai = Facebook_scraper(name, posts_count, browser,proxy=proxy, timeout=timeout, headless=headless)
    json_data = meta_ai.scrap_to_json()
    results.append(json_data)
    print(results)`

The first iteration was successful, but the next iteration still scrapes the first page_names. Is this because every iteration the cache was not deleted, or is there any approach that I can reach my objective?

**Comment by shaikhsajid1111** [comment]
Oh, Okay have you tried setting `headless` to `Fals`e to see if the browser is really scraping the same pages?

**Comment by kokohandoko00** [comment]
I have just try write the headless to be `False` and the browser scraping in different pages. But when I print the results, the results keep write the first page. My suspect is there is a problem on a way I append the data. Can you give me a clue about it?

**Comment by shaikhsajid1111** [comment]
Try printing `json_data` on every iteration that would help to debug

**Comment by thoriqfy** [comment]
actually i have the same problem. it occur when i try to scrap multiple names. but it will normally worked when did the scrap one call by one call. can you provide an example on how to iterate over a list of page name? thank you very much

**Comment by shaikhsajid1111** [comment]
That's right and weird at the same time why dictionary isn't appending to list. Work around would be to use dictionary for storing different page data. Like so

```python
import json
from facebook_page_scraper import Facebook_scraper
pages = ['metaai','mysql']

res = {}

for pg in pages:
    instance = Facebook_scraper(pg, 5, 'firefox', headless = False)
    json_data = instance.scrap_to_json()
    res[pg] = json.loads(json_data)

print(res)
```

**Comment by thoriqfy** [comment]
I still excperiencing the same things, I try to print every scrape, the output still giving the first iteration. This is my output:
![image](https://user-images.githubusercontent.com/55296421/215337300-27e48715-0d87-4556-a5a1-1477ba47b31d.png)

**Comment by shaikhsajid1111** [comment]
@thoriqfy yes this will happen because CSV file is written in write mode so it discard previous data. I think you should use dynamic like keep the filename same as Facebook page

**Comment by kokohandoko00** [comment]
Finally It can be resolved using argparse. Thanks in advance. But I have another issue that I want to ask
