### ISSUE TITLE
Always stuck until timeout.

### ISSUE THREAD

**Issue by mahmoudtamerali** [shaikhsajid1111/facebook_page_scraper#86]
edited: the problem has been solved.
### **The script was working properly with me about two weeks ago, but now keeps stuck until timeout.**
I tried to know the source of the problem and made **(headless = false)**, what I found was that the pop up that asks me to log in is no longer has the (X) button that closes it.

![newone](https://github.com/shaikhsajid1111/facebook_page_scraper/assets/144492568/cb1a6712-ae2f-4e57-a904-546accf7ed75)

May be its update from Facebook, I don't know.

I found this picture in older issue (84) [link to the older issue](https://github.com/shaikhsajid1111/facebook_page_scraper/issues/84)
 it shows that the (X) button was actually there at 8 august

![259163281-c7e546f4-5ce1-4e39-b7ff-a4d2cf626984](https://github.com/shaikhsajid1111/facebook_page_scraper/assets/144492568/b228cec6-e604-4e96-8840-f5641b4e944b)

### My question is:
 "**Is it just me who encounter that problem or it's really because of some Facebook updates? and is there is a solution other than need for login or cookies? will the scripts be updated if it found out its now not working fine for all, what if Iam only interested in the first post can I get fast way to that post without handling with the popup?**"

I think the problem isn't with my packages as it was working fine.
also, I don't think it's from proxy as I tried a lot of different proxies and even without proxy.
I tried chrome ==> the same result.
thanks in advance.

**Comment by Irene933** [comment]
This was fixed for me on login. The old image is at the moment you access the page so you can close it normaly but to scroll further facecbook stops you at some point like if you wish to see more you MUST login at this point. There not even an "X" button.
